### ISSUE TITLE
魅族note 8 重启进入桌面失败

### ISSUE THREAD

**Issue by rawer886** [bigsinger/AndroidIdChanger#83]
E/libc: Access denied finding property "ro.serialno"

 Process: com.meizu.flyme.launcher, PID: 28376
    java.lang.RuntimeException: Unable to create application com.meizu.flyme.launcher.LauncherApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.meizu.flyme.b.d.a(com.meizu.flyme.b.d$a)' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5998)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6758)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.meizu.flyme.b.d.a(com.meizu.flyme.b.d$a)' on a null object reference
        at com.meizu.flyme.launcher.aw.<init>(SourceFile:181)
        at com.meizu.flyme.launcher.aw.a(SourceFile:138)
        at com.meizu.flyme.launcher.LauncherApplication.onCreate(SourceFile:138)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1121)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5995)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6758) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by cuihua0** [comment]
你好，我跟你的情况类似，我的华为honor8x，能进入桌面，但是加载不出来东西，只有桌面。请问你的解决了吗？
