### ISSUE TITLE
Error sometimes device reboot

### ISSUE THREAD

**Issue by krolaper** [bigsinger/AndroidIdChanger#99]
My device bug. Sometimes device reboot
Log:
```
----part 1 start----
[ 2023-02-02T13:05:56.955     1000:  1609:  1609 I/LSPosed-Bridge  ] Loading module com.thinkdifferent.anywebview from /data/app/com.thinkdifferent.anywebview--thn_ntSngoHztC8gk0Ifg==/base.apk
[ 2023-02-02T13:05:56.959     1000:  1609:  1609 I/LSPosed-Bridge  ]   Loading class com.thinkdifferent.anywebview.AnyWebView
[ 2023-02-02T13:05:56.962     1000:  1609:  1609 I/LSPosed-Bridge  ] Loading module com.coderstory.toolkit from /data/app/com.coderstory.toolkit-1xpKfIHlfHfsahcMgj1qJg==/base.apk
[ 2023-02-02T13:05:56.963     1000:  1609:  1609 I/LSPosed-Bridge  ]   Loading class toolkit.coderstory.MainHook
[ 2023-02-02T13:05:56.981     1000:  1609:  1609 I/LSPosed-Bridge  ] Loading module com.bigsing.changer from /data/app/com.bigsing.changer-lpNJQAMNIVFGWFxeY9pCIQ==/base.apk
[ 2023-02-02T13:05:57.047     1000:  1609:  1609 I/LSPosed-Bridge  ]   Loading class com.bigsing.changer.MainHook
[ 2023-02-02T13:05:59.616     1000:  1609:  1609 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: android.os.Binder#execTransact(int,int,int,int)#exact
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.h(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at com.bigsing.changer.b.b.a(SourceFile:2)
	at com.bigsing.changer.MainHook.handleLoadPackage(SourceFile:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.ContextImpl.getClassLoader(ContextImpl.java:371)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6965)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7169)
	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:7550)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1002)
	at com.android.server.SystemServer.run(SystemServer.java:529)
	at com.android.server.SystemServer.main(SystemServer.java:356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
[ 2023-02-02T13:06:30.565    10243:  4082:  4082 I/LSPosed-Bridge  ] Loading module com.bigsing.changer from /data/app/com.bigsing.changer-lpNJQAMNIVFGWFxeY9pCIQ==/base.apk
[ 2023-02-02T13:06:30.623    10243:  4082:  4082 I/LSPosed-Bridge  ]   Loading class com.bigsing.changer.MainHook
[ 2023-02-02T13:06:30.852    10243:  4082:  4082 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: android.os.Binder#execTransact(int,int,int,int)#exact
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.h(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at com.bigsing.changer.b.b.a(SourceFile:2)
	at com.bigsing.changer.MainHook.handleLoadPackage(SourceFile:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1193)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by krolaper** [comment]
LSPosedlast version, module last version

**Comment by krolaper** [comment]
LSPosedlast version, module last version

**Comment by krolaper** [comment]
LSPosedlast version, module last version

**Comment by krolaper** [comment]
LSPosed last version, module last version
